config/routes.rb
Rails.application.routes.draw do
  resources :text_blocks
  get 'welcome/home'
  get 'welcome/new_book'
  get 'welcome/new_page'
  get 'welcome/new_worksheet'
  get 'welcome/new_feedback_collector'
  get 'welcome/new_message'
  get 'welcome/back_to_dashboard'

  root 'pages#home'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/text_block.rb
class TextBlock < ApplicationRecord
  belongs_to :user
  has_rich_text :body
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :text_blocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/text_blocks_controller.rb
class TextBlocksController < ApplicationController
  before_action :set_text_block, only: [:show, :edit, :update, :destroy]

  def index
    @text_blocks = TextBlock.all
  end

  def show
    @text_block = TextBlock.find(params[:id])
  end

  def new
    @text_block = TextBlock.new
  end

  def edit
    @text_block = TextBlock.find(params[:id])
  end

  def create
    @text_block = TextBlock.new(text_block_params)
    respond_to do |format|
      if @text_block.save
        format.html { redirect_to @text_block, notice: 'Text block was successfully created.' }
        format.json { render :show, status: :created, location: @text_block }
      else
        format.html { render :new }
        format.json { render json: @text_block.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @text_block.update(text_block_params)
        format.html { redirect_to @text_block, notice: 'Text block was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_block }
      else
        format.html { render :edit }
        format.json { render json: @text_block.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @text_block.destroy
    respond_to do |format|
      format.html { redirect_to text_blocks_url, notice: 'Text block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_text_block
    @text_block = TextBlock.find(params[:id])
  end

  def text_block_params
    params.require(:text_block).permit(:title, :body, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end

  def new_book
  end

  def new_page
  end

  def new_worksheet
  end

  def new_feedback_collector
  end

  def back_to_dashboard
  end

  def new_message
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/text_blocks_helper.rb
module TextBlocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MskPaperMoon
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/pages/home.html.haml
%h1
  Testing hot-reload

- if current_user
  = link_to "Sign Out", destroy_user_registration_path, method: :delete
-else
  = link_to "Sign In", new_user_session_path
  = link_to  "Sign Up", new_user_registration_path

app/views/text_blocks/_form.html.haml
= form_for @text_block do |f|
  .field
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .field
    = f.label :body
    = f.rich_text_area :body

  .field
    %button{:type=> 'submit', :class=> 'btn btn-success'}
      Save
      
- if @text_block.errors.any?
  #error_explanation
    %h2= "#{pluralize(@text_block.errors.count, "error")} prohibited this text_block from being saved:"
    %ul
      - @text_block.errors.full_messages.each do |message|
        %li= message

app/views/text_blocks/edit.html.haml
%h1 Editing text_block

= render 'form'

= link_to 'Show', @text_block
\|
= link_to 'Back', text_blocks_path

app/views/text_blocks/index.html.haml
%h1 Listing text_blocks

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @text_blocks.each do |text_block|
      %tr
        %td= link_to 'Show', text_block
        %td= link_to 'Edit', edit_text_block_path(text_block)
        %td= link_to 'Destroy', text_block, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Text block', new_text_block_path

app/views/text_blocks/new.html.haml
%h1 New text_block

= render 'form'

= link_to 'Back', text_blocks_path

app/views/text_blocks/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_text_block_path(@text_block)
\|
= link_to 'Back', text_blocks_path

app/views/welcome/back_to_dashboard.html.haml
%h1 Dashboard

%ul
  %li From now on this is the view you will get when you log in
  %li You can see your ideabok, its tags, and worksheets
  %li you can also browse the concept cards, you used these before during your alignment worksheet
  %li And notifications - when you have a new item it will you can check up here. Click the notification to proceed.

= link_to "New Message", welcome_new_message_path

app/views/welcome/home.html.haml
%h1 Welcome Outline

%ul
  %li overview of concept
  %li all starts with an idea book
  %li click on one to continue

= link_to "An idea book", welcome_new_book_path

app/views/welcome/new_book.html.haml
%h1 A new idea book

%ul
  %li an idea book is where you can write an concept you'd like. It's all private.
  %li each page allows you to write, add links, pinterest pins, and upload your own images
  %li let's go ahead an create our first page

= link_to "Your first idea", welcome_new_page_path

app/views/welcome/new_feedback_collector.html.haml
%h1 Feedback

%ul
  %li There are different types of feedback collectors you can create for your concept they include [Peer Notes]
  [Quick Survey] [Multiple Choice] [Value Check Up]. Let's pick [Peer Notes] - this will allow you to get some input
  from a colleague that's working on the themes you previously identified.
  %li Select [Jackie Paper] from the available list of colleagues, add a note if you'd like and send it on its way.

= link_to "Head back to the dashboard", welcome_back_to_dashboard_path

app/views/welcome/new_message.html.haml
%h1
  New Message

%ul
  %li Looks like Jackie is asking us to rethink some of our ideas. You can keep going in your idea book and follow the
  same process. Itteration is the key to concept development - so don't feel rejected, your ideas will be archived here,
  and who knows how it might come back or be recycled.
  %li Best of Luck

app/views/welcome/new_page.html.haml
%h1 New Page

%ul
  %li Go ahead and just start writing. Don't worry about anything else.
  %li Great, now let's add some tags to help you find this better. Use tags to help you bring together your ideas.
  %li If you ever don't know quite where you're going with an idea just leave it untagged and it will be sorted as uncategorized. This can be helpful later to clean up your idea book.
  %li Excellent. Now let's add some images. You can upload from your desktop or paste in a URL
  %li This works with Pinterest, if you're your a pinterest user go ahead an create a new board if not you can skip this step
  %li Awesome! You got your concept out - that's half the battle
  %li Now, let's see how your idea can work with the strategy Moleskine is currently working toward. To do this we'll fill
  out a worksheet. Worksheets attach to your idea book and help build the concept and business case for your idea. Let's
  get started.

= link_to "Worksheet: Alignment", welcome_new_worksheet_path

app/views/welcome/new_worksheet.html.haml
%h1 New Worksheet

%ul
  %li The first and most common worksheet is Alignment. This allows you to understand how your idea might work with with
  what others in the company are doing as well as achieve the goals Moleskine has set for the near future.
  %li In this system there are a number of Concept Cards that reflect these goals and projects let's look through them
  and see if we can find a match for your idea (you need at least one). Dont' worry if your idea fits more than one of these concept cards,
  for now just pick the one think matches most or you'd like to start with.
  %li Audience - [Business] [Art] [Planner] [Gen Z] [Female Centric] [Somebody Else]
  %li Category - [Paper] [Digital-Physical] [Licensed] [Something New]
  %li Trends - [Customization] [Subscription] [Gift Giving] [Something Else]
  %li You said your idea is for Female Centric audience, in the paper category. Fill out the following questions.
  %li Great! Now we can begin to speak to the right peers and understand where your great idea could live. There's one more thing we need to do
  and that is to get some feedback.
  %li Feedback Collectors are a way that you discuss your idea with colleagues and sharpen its offering.


= link_to "Get some feedback", welcome_new_feedback_collector_path